FROM astrocrpublic.azurecr.io/runtime:3.2-4

# Variables de entorno del proyecto
ENV PROJECT_ROOT=/usr/local/airflow/project
ENV DBT_PROJECT_DIR=/usr/local/airflow/project/dbt
ENV DBT_PROFILES_DIR=/usr/local/airflow/project/dbt
